export const cities = [
  { id: 1, name: "Manama" },
  { id: 2, name: "Muharraq" },
  { id: 3, name: "Riffa" },
  { id: 4, name: "Hamad Town" },
  { id: 5, name: "Isa Town" },
  { id: 6, name: "Sitra" },
  { id: 7, name: "Budaiya" },
  { id: 8, name: "Adliya" },
  { id: 9, name: "Amwaj Islands" },
  { id: 10, name: "Arad" },
  { id: 11, name: "Bani Jamra" },
  { id: 12, name: "Barbar" },
  { id: 13, name: "Diyar Al Muharraq" },
  { id: 14, name: "Durrat Al Bahrain" },
  { id: 15, name: "Hidd" },
  { id: 16, name: "Jid Ali" },
  { id: 17, name: "Jidhafs" },
  { id: 18, name: "Juffair" },
  { id: 19, name: "Karrana" },
  { id: 20, name: "Karzakkan" },
  { id: 21, name: "Malikiya" },
  { id: 22, name: "Sanabis" },
  { id: 23, name: "Seef" },
  { id: 24, name: "Saar" },
  { id: 25, name: "Tubli" },
  { id: 26, name: "Zallaq" },
  { id: 27, name: "Bu Quwah" },
  { id: 28, name: "Abu Saiba" },
  { id: 29, name: "Umm Al Hassam" },
  { id: 30, name: "Al Jasra" },
  { id: 31, name: "Nuwaidrat" },
  { id: 32, name: "Samaheej" },
  { id: 33, name: "Busaiteen" },
  { id: 34, name: "Galali" },
  { id: 35, name: "Nabih Saleh" },
  { id: 36, name: "Salmabad" },
  { id: 37, name: "Al Dair" },
  { id: 38, name: "Ghuraifa" },
  { id: 39, name: "Awali" },
  { id: 40, name: "Diraz" },
  { id: 41, name: "Halat Bu Maher" },
  { id: 42, name: "Gudaibiya" },
  { id: 43, name: "Bilad Al Qadeem" },
  { id: 44, name: "Halat Seltah" },
  { id: 45, name: "Khamis" },
  { id: 46, name: "Ma'ameer" },
  { id: 47, name: "Askar" },
  { id: 48, name: "Hamala" },
  { id: 49, name: "Halat Nuaim" },
  { id: 50, name: "Al Daih" },
  { id: 51, name: "Jaww" },
  { id: 52, name: "Markh" },
  { id: 53, name: "Abu Ithham" },
  { id: 54, name: "Samahij" },
  { id: 55, name: "Karranah" },
  { id: 56, name: "Karzakan" },
  { id: 57, name: "Other" },
];

// Reorder the cities array in alphabetical order by name
cities.sort((a, b) => a.name.localeCompare(b.name));
